In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../digit-recognizer/train.csv')
df.head(5)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
labels = df['label']
labels[:5]

0    1
1    0
2    1
3    4
4    0
Name: label, dtype: int64

In [7]:
features = df.drop('label', axis=1)
features.head(5)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# Standard normalisation:
from sklearn.preprocessing import StandardScaler
features = StandardScaler().fit_transform(features)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

In [22]:
# get eigen values and eigenvectors

# covariance matrix
covar = np.matmul(features.T, features)
print(covar.shape)
from scipy.linalg import eigh
values, vectors = eigh(covar, eigvals=(782,783))

(784, 784)

In [26]:
new_coordinates = np.matmul(vectors.T, features.T)

In [27]:
new_coordinates

array([[-5.2264454 ,  6.03299601, -1.70581328, ...,  7.07627667,
        -4.34451279,  1.55912058],
       [-5.14047772, 19.29233234, -7.64450341, ...,  0.49539137,
         2.30724011, -4.80767022]])